### ISSUE TITLE
Revise documentation on Configuration Management

### ISSUE THREAD

**Issue by cyunis** [tetrabiodistributed/tetra#3]
Need to be more descriptive. Maybe some of the sections should be split into more pages instead of being lumped together.

- [ ] separate configuration management into: hardware versioning, software version control, documentation guidelines/principles, workflow process/change management (hardware and software can also be one page)
- [ ] update documentation on posting discussion notes in github issues
- [ ] update documentation on CAD/STL files should have an associated drawing
- [ ] update documentation on drawings should have a reviewer

**Comment by capsulecorplab** [comment]
As of https://github.com/tetrabiodistributed/project-tetra-docs/commit/49ba0ad1c3f039064e8eef1ec2d8e2f2c6da26fb, the description under Configuration Management and Contributing Guidelines is _"Documentation, change management, & version control guidelines"_ and _"How to contribute to the docs"_, respectively. Did you have an alternative title & descriptions in mind? What sections could we split into separate pages?

**Comment by cyunis** [comment]
Each word should be its own page or the headers should be big af and stand out on the page to mark separation between the documentation.

**Comment by cyunis** [comment]
Configuration Management splits (each its own page): hardware versioning, software version control, documentation guidelines/principles, workflow process/change management  (hardware and software can also be one page)

**Comment by cyunis** [comment]
catherine will create a pull request at some point to change verbiage for 'updating the website' section in configuration management. 
we are also gonna work on those header titles
