### ISSUE TITLE
Add list of contributors

### ISSUE THREAD

**Issue by capsulecorplab** [tetrabiodistributed/tetra#38]
Add list of contributors to README

**Comment by mmroden** [comment]
Mark Roden, PhD | Product Manager, Testing, Printing, Photography

**Comment by Judoguy12** [comment]
Jamie Waters | Outreach and Project Manager| Worcester, England, UK

**Comment by mechatroniks-git** [comment]
Patrick Campbell | Electromechanical Design Engineering | Los Angeles, CA

**Comment by hydronics2** [comment]
Thomas Hudson| Electromechanical Design Engineering | Portland, OR

**Comment by adebuleo** [comment]
Oluwafemi Adebule | Project Manager | Toronto Canada

**Comment by adebuleo** [comment]
Oluwafunmiladeayo Adebule | Development Baby

**Comment by professor-nimrod** [comment]
Hey @fpdotmonkey, here's the list of everyone from @cyunis's webpage. Mine can stay the same:

Burhan Qaddoumi | Design & Simulation Engineer | Corning, NY, USA

Catherine Yunis | Writing, Testing and Assembly | Los Angeles, CA, USA

**Christopher Molinari | Documentation, Outreach | Methuen, MA, USA**

Daniel Stemen RCP | Clinical Validation and Testing | Los Angeles, CA, USA

Darryl H. Hwang, PhD | Additive Manufacturing and Design Support | Los Angeles, CA, USA

Hannah Fink | Industrial Design | San Francisco, CA, USA

Jamie Waters | Outreach and Project Manager| Worcester, England, UK

John Brooks, MS | Visual Media | Ventura, CA, USA

John Grano | Design & Manufacturing Engineer | Denver, CO, USA

Linda Yan | Media | Bellevue, Washington, USA

Mark Roden, PhD | Product Manager, Assembly, and Testing | Sherman Oaks, CA, USA

Oluwafemi Adebule | Project Manager | Toronto, ON, Canada

Patrick Campbell | Electromechanical Design Engineer | Los Angeles, CA, USA

Sean Marquez | Software & Systems Engineering, Documentation | Los Angeles, CA, USA

Thomas Hudson | Electromechanical Design Engineer | Portland, OR, USA

Valerie Seabaugh MD | Clinical Advisement and Testing | Los Angeles, CA, USA

**Comment by lindayanyan** [comment]
Linda Yan | Media | Bellevue, WA
