### ISSUE TITLE
Remove links to google drive 

### ISSUE THREAD

**Issue by cyunis** [tetrabiodistributed/tetra#4]
In the references page there shouldn't be resources hosted on google drive, we should migrate them to the site

**Comment by capsulecorplab** [comment]
Created a working branch, [cleanup-references](https://github.com/tetrabiodistributed/project-tetra-docs/tree/cleanup-references), to facilitate deleting/migrating content from google docs. @Judoguy12 can we delete or migrate the 4 google doc links in [references](https://tetrabiodistributed.github.io/project-tetra-docs/references/)?

**Comment by capsulecorplab** [comment]
If still relevant, I'm thinking [Testing Questions](https://docs.google.com/document/d/164DD9j-OUmsBKB3FELcanB-5L1GkFy0qX10EiUfEtjM/edit) should have a section under [explanations](https://tetrabiodistributed.github.io/project-tetra-docs/explanations/), and the [google slide](https://docs.google.com/presentation/d/1UeSRyUB0dAOZZecX4TGh40GkVtGADlXzBOwVFjPqIFE/edit#slide=id.g721f325637_2_2) should probably go under [Project Overiew](https://tetrabiodistributed.github.io/project-tetra-docs/explanations/overview/). I'm not sure about the other two.

**Comment by Judoguy12** [comment]
Testing as is old so is printing queue, project proposal can be deleted and the system diagram I think is also out of date

**Comment by professor-nimrod** [comment]
https://files.slack.com/files-pri/TUTSYURT3-F015PDK962F/screenshot_from_2020-06-18_13-16-17.png
Can this diagram be uploaded? This issue seems simple enough; I can work on it

**Comment by capsulecorplab** [comment]
> https://files.slack.com/files-pri/TUTSYURT3-F015PDK962F/screenshot_from_2020-06-18_13-16-17.png
> Can this diagram be uploaded? This issue seems simple enough; I can work on it

@chrismolinari456 that diagram is already statically generated with `plantuml` via the `asciidoctor-diagram` extension from [ibd-system-ventilator-splitter-assembly-airflow.puml](https://github.com/tetrabiodistributed/project-tetra/blob/mbse/system_model/ibd-system-ventilator-splitter-assembly-airflow.puml) and viewable on the [overview](https://tetrabiodistributed.github.io/project-tetra-docs/explanations/overview/#_overview) page. Check #22 for recent updates.

**Comment by capsulecorplab** [comment]
Issue #9 should add an embedded plantuml generated diagram in a dedicated page under [references](https://tetrabiodistributed.github.io/project-tetra-docs/references/), which should also be statically generated from [ibd-system-ventilator-splitter-assembly-airflow.puml](https://github.com/tetrabiodistributed/project-tetra/blob/mbse/system_model/ibd-system-ventilator-splitter-assembly-airflow.puml), which #22 will enable.
